# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inst_dep_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inst_dep_record.proto',
  package='ProtoMessage',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15inst_dep_record.proto\x12\x0cProtoMessage\"]\n\x13InstDepRecordHeader\x12\x0e\n\x06obj_id\x18\x01 \x02(\t\x12\x0e\n\x03ver\x18\x02 \x01(\r:\x01\x30\x12\x11\n\ttick_freq\x18\x03 \x02(\x04\x12\x13\n\x0bwindow_size\x18\x04 \x02(\r\"\xb6\x02\n\rInstDepRecord\x12\x0f\n\x07seq_num\x18\x01 \x02(\x04\x12=\n\x04type\x18\x02 \x02(\x0e\x32&.ProtoMessage.InstDepRecord.RecordType:\x07INVALID\x12\x0e\n\x06p_addr\x18\x03 \x01(\x04\x12\x0c\n\x04size\x18\x04 \x01(\r\x12\r\n\x05\x66lags\x18\x05 \x01(\r\x12\x0f\n\x07rob_dep\x18\x06 \x03(\x04\x12\x12\n\ncomp_delay\x18\x07 \x02(\x04\x12\x0f\n\x07reg_dep\x18\x08 \x03(\x04\x12\x0e\n\x06weight\x18\t \x01(\r\x12\n\n\x02pc\x18\n \x01(\x04\x12\x0e\n\x06v_addr\x18\x0b \x01(\x04\x12\x0c\n\x04\x61sid\x18\x0c \x01(\r\"8\n\nRecordType\x12\x0b\n\x07INVALID\x10\x00\x12\x08\n\x04LOAD\x10\x01\x12\t\n\x05STORE\x10\x02\x12\x08\n\x04\x43OMP\x10\x03')
)



_INSTDEPRECORD_RECORDTYPE = _descriptor.EnumDescriptor(
  name='RecordType',
  full_name='ProtoMessage.InstDepRecord.RecordType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOAD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMP', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=389,
  serialized_end=445,
)
_sym_db.RegisterEnumDescriptor(_INSTDEPRECORD_RECORDTYPE)


_INSTDEPRECORDHEADER = _descriptor.Descriptor(
  name='InstDepRecordHeader',
  full_name='ProtoMessage.InstDepRecordHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obj_id', full_name='ProtoMessage.InstDepRecordHeader.obj_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ver', full_name='ProtoMessage.InstDepRecordHeader.ver', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tick_freq', full_name='ProtoMessage.InstDepRecordHeader.tick_freq', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window_size', full_name='ProtoMessage.InstDepRecordHeader.window_size', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=132,
)


_INSTDEPRECORD = _descriptor.Descriptor(
  name='InstDepRecord',
  full_name='ProtoMessage.InstDepRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='ProtoMessage.InstDepRecord.seq_num', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ProtoMessage.InstDepRecord.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p_addr', full_name='ProtoMessage.InstDepRecord.p_addr', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='ProtoMessage.InstDepRecord.size', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='ProtoMessage.InstDepRecord.flags', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rob_dep', full_name='ProtoMessage.InstDepRecord.rob_dep', index=5,
      number=6, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comp_delay', full_name='ProtoMessage.InstDepRecord.comp_delay', index=6,
      number=7, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reg_dep', full_name='ProtoMessage.InstDepRecord.reg_dep', index=7,
      number=8, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='ProtoMessage.InstDepRecord.weight', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pc', full_name='ProtoMessage.InstDepRecord.pc', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_addr', full_name='ProtoMessage.InstDepRecord.v_addr', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asid', full_name='ProtoMessage.InstDepRecord.asid', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSTDEPRECORD_RECORDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=445,
)

_INSTDEPRECORD.fields_by_name['type'].enum_type = _INSTDEPRECORD_RECORDTYPE
_INSTDEPRECORD_RECORDTYPE.containing_type = _INSTDEPRECORD
DESCRIPTOR.message_types_by_name['InstDepRecordHeader'] = _INSTDEPRECORDHEADER
DESCRIPTOR.message_types_by_name['InstDepRecord'] = _INSTDEPRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstDepRecordHeader = _reflection.GeneratedProtocolMessageType('InstDepRecordHeader', (_message.Message,), dict(
  DESCRIPTOR = _INSTDEPRECORDHEADER,
  __module__ = 'inst_dep_record_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMessage.InstDepRecordHeader)
  ))
_sym_db.RegisterMessage(InstDepRecordHeader)

InstDepRecord = _reflection.GeneratedProtocolMessageType('InstDepRecord', (_message.Message,), dict(
  DESCRIPTOR = _INSTDEPRECORD,
  __module__ = 'inst_dep_record_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMessage.InstDepRecord)
  ))
_sym_db.RegisterMessage(InstDepRecord)


# @@protoc_insertion_point(module_scope)
